name: Update Evento Data
permissions:
  contents: write

on:
  schedule:
    - cron: "*/5 * * * *"  # Every 5 minutes
  workflow_dispatch:       # Allow manual trigger

env:
  F_RESULTS: docs/data/survey_65x4qkp9_results.json
  F_TIMESTAMPS: docs/data/survey_65x4qkp9_timestamps.json

jobs:
  fetch-json:
    runs-on: ubuntu-latest
    steps:

      - name: Install jq
        run: sudo apt-get install jq

      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Fetch Evento JSON
        run: |
          curl -s "https://evento.renater.fr/rest.php/survey/65x4qkp9/results?format=download:json:;&tz=Europe%2FParis" -o "$F_RESULTS"

      - name: Update vote timestamps
        run: src/bash/update_vote_timestamps.bash "$F_RESULTS" "$F_TIMESTAMPS"

      - name: Commit and push if changed
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add "$F_RESULTS" "$F_TIMESTAMPS"
          git diff --cached --quiet || git commit -m "Update data.json from Evento"
          git push --force-with-lease
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
