name: Update Evento Data
permissions:
  contents: write

on:
  schedule:
    - cron: "0 12 * * *" 
  workflow_dispatch:       # Allow manual trigger

env:
  F_RESULTS: ${{ github.workspace }}/docs/data/survey_65x4qkp9_results.json
  F_TIMESTAMPS: ${{ github.workspace }}/docs/data/survey_65x4qkp9_timestamps.json

jobs:
  but3:
    runs-on: ubuntu-latest
    steps:

      - name: Install deps
        run: sudo apt-get update && sudo apt-get install jq bash

      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Fetch Evento JSON
        run: |
          curl -s "https://evento.renater.fr/rest.php/survey/65x4qkp9/results?format=download:json:;&tz=Europe%2FParis" -o "$F_RESULTS"

      - name: Commit
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

          git add "$F_RESULTS"
          git commit -m "¤"

      - name: Update vote timestamps
        run: |
            bash ${{ github.workspace }}/src/bash/vote_timestamps_from_history.bash "$F_RESULTS" > "$F_TIMESTAMPS"

      - name: Amend commit with new timestamps
        run: |
            git add "$F_TIMESTAMPS"
            git commit --amend -m "Update data.json from Evento"

      - name: Push
        run: |
          git push --force-with-lease
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
